"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Confronto_1 = require("./Inimigos/Confronto");
const Dragao_1 = require("./Inimigos/Dragao");
const Pocao_1 = require("./Inventario/Pocao");
const TiposENUMs_1 = require("./Inventario/TiposENUMs");
const Bardo_1 = require("./Personagens/Bardo");
// import { tocarSom } from "./Auxiliares/sons";
const p1 = new Bardo_1.Bardo('Bardo teste juliana');
const pocao1 = new Pocao_1.Pocao('Poção de cura', TiposENUMs_1.EfeitoPocao.CURA);
const pocao2 = new Pocao_1.Pocao('Poção de Forca', TiposENUMs_1.EfeitoPocao.FORCA);
const bicho = new Dragao_1.Dragao();
(0, Confronto_1.iniciarConfronto)(p1, bicho);
