"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Auxiliares_1 = require("./Auxiliares/Auxiliares");
const Confronto_1 = require("./Inimigos/Confronto");
const Fantasma_1 = require("./Inimigos/Fantasma");
const CriaPersonagem_1 = require("./Personagens/CriaPersonagem");
let personagem = (0, CriaPersonagem_1.criaPersonagem)();
(0, Auxiliares_1.clear)();
(0, Auxiliares_1.arteInfoJogo)();
(0, Auxiliares_1.stop)();
let fada = new Fantasma_1.Fantasma();
(0, Confronto_1.iniciarConfronto)(personagem, fada);
